name: reclutamiento de Agente

#on: push
on:
  workflow_dispatch:

jobs:
    reporte-de-reclutamiento:
        runs-on: ubuntu-latest

        steps:
            - name: El agente se presenta
              run: echo "Soy Lex Luthor, y el lider la Legion del  Mal"
              
            - name: Reporte de identidad
              run: |
                echo "Nombre: Lex Luthor"
                echo "Edad: 45"
                echo "Ocupación: Empresario y Villano"
                echo "Habilidades: Genio, Estratega, Manipulador"
                echo "Objetivo: Derrotar a Superman y dominar el mundo"
                echo "===================="
                echo ""
                echo "Nombre clave: ${{ github.actor }}"
                echo ""
                echo "Contexto de github"
                echo "Repositorio: ${{ github.repository }}"
                echo "Operacion: ${{ github.sha }}"
                echo "Metadata: ${{ toJSON(github) }}"


            - name: Capacidadades del Agente
              run: |
                echo "Capacidades detectadas:"
                echo " Sistema operativo:"
                uname -a
                echo "- Recursos financieros ilimitados"
                echo "- Acceso a tecnología avanzada"
                echo "- Red de contactos y aliados"
                git --version
                python3 --version

            - name: Reconocimiento del terreno
              run: |
                echo "Reconocimiento del terreno:"
                ls /